name: Deploy arfx-admin website to azure blob storage

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest    
    steps:     
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Build Application
      run: |
         yarn install
         yarn build
        
  Deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest 
    steps:
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
      with:
        source-path: build
        sas-url: https://electronstorageaccount.blob.core.windows.net/?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-02-20T16:48:24Z&st=2021-02-20T08:48:24Z&spr=https&sig=KDzBh7N8JL2lEXMhPsTBnP8kbyKi78pPB0MTii3qS58%3D
