name: Deploy arfx-admin website to azure blob storage

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest    
    steps:     
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        
    - name: Build Application
      run: |
         yarn install
         yarn build
        
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest 
    steps:
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
      with:
        source-path: build
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
