name: Deploy arfx-admin website to azure blob storage

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest    
    steps:     
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        
    - name: Build Application
      run: |
         yarn install
         yarn build
         
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
         name: artifacts
         path: build/
         retention-days: 1
        
  Deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest 
    
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
         name: artifacts
         path: build/
         
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
      with:
        enabled-static-website: 'true'
        source-path: build
        sas-url: https://electronapps.blob.core.windows.net/?sv=2020-02-10&ss=bfqt&srt=sco&sp=rwdlacupx&se=2021-02-21T00:57:38Z&st=2021-02-20T16:57:38Z&spr=https&sig=IoVJY%2Bl4rNlYonH5QNWf0JBw0UkQKUM1t2HIjyTynWY%3D
